/**
 * LessonFlow service worker -- FR-APP-02, fully usable with no network.
 *
 * GENERATED by the `lessonflow-service-worker` plugin in `apps/web/vite.config.ts`.
 * Do not edit this file; edit the plugin.
 *
 * Every asset is precached at install, so the app is offline-ready after one visit rather
 * than after happening to have visited each screen. Nothing here syncs or uploads: every byte
 * of the user's data is already local (FR-DATA-01), so offline needs no data work at all.
 */

const CACHE = 'lessonflow-299d87d5f3db'
const BASE = "/lessonflow-app/"
const PRECACHE = [
  "/lessonflow-app/",
  "/lessonflow-app/apple-touch-icon.png",
  "/lessonflow-app/assets/index-C6xHUsg2.js",
  "/lessonflow-app/assets/index-DVQja8eh.css",
  "/lessonflow-app/assets/index-P0NByPvA.js",
  "/lessonflow-app/icon-192.png",
  "/lessonflow-app/icon-512.png",
  "/lessonflow-app/icon-maskable-512.png",
  "/lessonflow-app/manifest.webmanifest"
]

self.addEventListener('install', (event) => {
  // `skipWaiting` so a returning user gets the new build on the next load rather than after
  // closing every tab. Safe here because the caches are keyed by content hash: an old page
  // never ends up asking a new cache for an asset name that moved.
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting()))
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((names) => Promise.all(names.filter((name) => name !== CACHE).map((name) => caches.delete(name))))
      .then(() => self.clients.claim()),
  )
})

self.addEventListener('fetch', (event) => {
  const request = event.request
  if (request.method !== 'GET') return

  const url = new URL(request.url)
  if (url.origin !== self.location.origin) return

  // A navigation to any path is the single-page app: answer it with the cached shell rather
  // than letting the browser show its offline page.
  if (request.mode === 'navigate') {
    event.respondWith(caches.match(BASE).then((hit) => hit ?? caches.match(BASE + 'index.html')).then((hit) => hit ?? fetch(request)))
    return
  }

  // Cache-first is correct precisely because the names are content-hashed: a cached asset can
  // never be a stale version of a different one. A miss is a file the build did not emit.
  event.respondWith(
    caches.match(request).then((hit) => {
      if (hit !== undefined) return hit
      return fetch(request).then((response) => {
        if (response.ok && response.type === 'basic') {
          const copy = response.clone()
          caches.open(CACHE).then((cache) => cache.put(request, copy))
        }
        return response
      })
    }),
  )
})
