/**
 * LessonFlow service worker -- FR-APP-02, fully usable with no network.
 *
 * GENERATED by the `lessonflow-service-worker` plugin in `apps/web/vite.config.ts`.
 * Do not edit this file; edit the plugin.
 *
 * Every asset is precached at install, so the app is offline-ready after one visit rather
 * than after happening to have visited each screen. Nothing here syncs or uploads: every byte
 * of the user's data is already local (FR-DATA-01), so offline needs no data work at all.
 */

const CACHE = 'lessonflow-69fc852e4c37'
const BASE = "/lessonflow-app/"
const PRECACHE = [
  "/lessonflow-app/",
  "/lessonflow-app/apple-touch-icon.png",
  "/lessonflow-app/assets/figtree-latin-500-normal-BWnGEVsr.woff2",
  "/lessonflow-app/assets/figtree-latin-500-normal-B_yy1phn.woff",
  "/lessonflow-app/assets/figtree-latin-600-normal-BM_oTo4n.woff",
  "/lessonflow-app/assets/figtree-latin-600-normal-Cv_xCTDl.woff2",
  "/lessonflow-app/assets/figtree-latin-700-normal-BCCt2T1q.woff",
  "/lessonflow-app/assets/figtree-latin-700-normal-th6qEP7c.woff2",
  "/lessonflow-app/assets/figtree-latin-800-normal-30yxI7TZ.woff2",
  "/lessonflow-app/assets/figtree-latin-800-normal-B7vj2UK8.woff",
  "/lessonflow-app/assets/figtree-latin-ext-500-normal-BOEJvrb_.woff",
  "/lessonflow-app/assets/figtree-latin-ext-500-normal-Du0rIuHj.woff2",
  "/lessonflow-app/assets/figtree-latin-ext-600-normal-CQqsimlV.woff",
  "/lessonflow-app/assets/figtree-latin-ext-600-normal-DJlfifZj.woff2",
  "/lessonflow-app/assets/figtree-latin-ext-700-normal-BoDi4KL2.woff",
  "/lessonflow-app/assets/figtree-latin-ext-700-normal-CS4sQkGV.woff2",
  "/lessonflow-app/assets/figtree-latin-ext-800-normal-Cp4dEvwL.woff",
  "/lessonflow-app/assets/figtree-latin-ext-800-normal-DLIuazCv.woff2",
  "/lessonflow-app/assets/index-BhN6GLia.js",
  "/lessonflow-app/assets/index-C6xHUsg2.js",
  "/lessonflow-app/assets/index-DhLQZBtT.css",
  "/lessonflow-app/assets/public-sans-latin-400-normal-8Rpg0ruU.woff2",
  "/lessonflow-app/assets/public-sans-latin-400-normal-SBbinRkI.woff",
  "/lessonflow-app/assets/public-sans-latin-500-normal-NlrCPXnF.woff2",
  "/lessonflow-app/assets/public-sans-latin-500-normal-vCxiVFAq.woff",
  "/lessonflow-app/assets/public-sans-latin-600-normal-BR59oU-I.woff",
  "/lessonflow-app/assets/public-sans-latin-600-normal-Fru-LXNs.woff2",
  "/lessonflow-app/assets/public-sans-latin-700-normal-BqJmxWdE.woff2",
  "/lessonflow-app/assets/public-sans-latin-700-normal-Dm-oTPSL.woff",
  "/lessonflow-app/assets/public-sans-latin-ext-400-normal-B02wwOdZ.woff",
  "/lessonflow-app/assets/public-sans-latin-ext-400-normal-mk90oQqJ.woff2",
  "/lessonflow-app/assets/public-sans-latin-ext-500-normal-BHCCp-na.woff",
  "/lessonflow-app/assets/public-sans-latin-ext-500-normal-DC-z7ASZ.woff2",
  "/lessonflow-app/assets/public-sans-latin-ext-600-normal-DchWdWJ_.woff2",
  "/lessonflow-app/assets/public-sans-latin-ext-600-normal-DfkbVac2.woff",
  "/lessonflow-app/assets/public-sans-latin-ext-700-normal-CgolUQuG.woff2",
  "/lessonflow-app/assets/public-sans-latin-ext-700-normal-jWHjnMgZ.woff",
  "/lessonflow-app/assets/public-sans-vietnamese-400-normal-BO1meqcx.woff",
  "/lessonflow-app/assets/public-sans-vietnamese-400-normal-TxZB8OSn.woff2",
  "/lessonflow-app/assets/public-sans-vietnamese-500-normal-CXYe29CY.woff",
  "/lessonflow-app/assets/public-sans-vietnamese-500-normal-DjztbcKe.woff2",
  "/lessonflow-app/assets/public-sans-vietnamese-600-normal-CcnAzmUX.woff",
  "/lessonflow-app/assets/public-sans-vietnamese-600-normal-P4BtCUdw.woff2",
  "/lessonflow-app/assets/public-sans-vietnamese-700-normal-D97ShjGS.woff2",
  "/lessonflow-app/assets/public-sans-vietnamese-700-normal-Dq5VrXjD.woff",
  "/lessonflow-app/icon-192.png",
  "/lessonflow-app/icon-512.png",
  "/lessonflow-app/icon-maskable-512.png",
  "/lessonflow-app/manifest.webmanifest"
]

// **`cache: 'reload'`, past the browser's HTTP cache.** GitHub Pages sends `max-age=600`, so a
// plain `addAll` within ten minutes of the last visit filled the NEW cache with the OLD
// `index.html` -- and kept it until the next deploy. Measured 2026-09-25 in real Chrome with
// Pages' headers: three reloads and the `Get the latest version` button all stayed on the old
// build. The hashed assets would be safe either way; the shell is the one that is not.
const fresh = () => PRECACHE.map((url) => new Request(url, { cache: 'reload' }))

self.addEventListener('install', (event) => {
  // `skipWaiting` so a returning user gets the new build on the next load rather than after
  // closing every tab. Safe here because the caches are keyed by content hash: an old page
  // never ends up asking a new cache for an asset name that moved.
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(fresh())).then(() => self.skipWaiting()))
})

// Only this app's OLD caches. The origin is shared with another live site (M70), and its caches
// are not this worker's to delete. The prefix is `isAppCache`'s in `reset.ts`.
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((names) => Promise.all(names.filter((name) => name.startsWith('lessonflow-') && name !== CACHE).map((name) => caches.delete(name))))
      .then(() => self.clients.claim()),
  )
})

self.addEventListener('fetch', (event) => {
  const request = event.request
  if (request.method !== 'GET') return

  const url = new URL(request.url)
  if (url.origin !== self.location.origin) return

  // A navigation to any path is the single-page app: answer it with the cached shell rather
  // than letting the browser show its offline page.
  //
  // No shell means this cache was deleted after install -- another site on the origin, or the
  // browser freeing space (M71). Answer from the network as before, and put the whole precache
  // back, so the NEXT launch with no signal opens. Before this, only a new worker's install did.
  // Offline, the refill fails quietly: there is nothing to answer with either way. Both calls are
  // made during dispatch, off one lookup: `waitUntil` is only honoured while the event is still
  // active, and registering it up front does not lean on `respondWith` still being pending.
  // (Chrome did accept a late one while it was, measured 2026-09-22 -- this is the safe order,
  // not the only working one.)
  if (request.mode === 'navigate') {
    const shell = caches.match(BASE).then((hit) => hit ?? caches.match(BASE + 'index.html'))
    event.waitUntil(
      shell
        .then((hit) => (hit === undefined ? caches.open(CACHE).then((cache) => cache.addAll(fresh())) : undefined))
        .catch(() => {}),
    )
    event.respondWith(shell.then((hit) => hit ?? fetch(request)))
    return
  }

  // Cache-first is correct precisely because the names are content-hashed: a cached asset can
  // never be a stale version of a different one. A miss is a file the build did not emit.
  event.respondWith(
    caches.match(request).then((hit) => {
      if (hit !== undefined) return hit
      return fetch(request).then((response) => {
        if (response.ok && response.type === 'basic') {
          const copy = response.clone()
          caches.open(CACHE).then((cache) => cache.put(request, copy))
        }
        return response
      })
    }),
  )
})
